### ISSUE TITLE
./configs/yolov5_exp/yolov5s_C3GC.yaml 请问这个C3GC是具体哪个网络来的？没有找到相关信息

### ISSUE THREAD

**Issue by LitChi-bit** [ShihaoHan19980609/T22_034_CRDDC_2022_SourceCode#1]
请问这个C3GC是GCNet还是什么东西，没有在网上检索到相关内容

**Comment by shyhoom** [comment]
你可以参考这个，Yue Cao, et al. "GCNet: Non-local Networks Meet Squeeze-Excitation Networks and Beyond.

**Comment by shyhoom** [comment]
是C3中融合了GCNet

**Comment by LitChi-bit** [comment]
明白了，非常感谢 : )
